---
version: '3.2'
volumes:
  mysql-data:

services:
  node:
    build: .
    environment:
      PORT: 3000
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: "user"
      DATABASE_PASSWORD: "password"
      DATABASE_NAME: "projet_film"
    volumes:
      - ./certs/:/myapp/certs/
    depends_on:
      - mysql
    ports:
      - 443:443
  mysql:
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "projet_film"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    ports:
     - 8082:80
    environment:
     - PMA_HOST=mysql
