Vue.component('menu_general', {
	template: '<div class="row mt-3 align-items-center">'
				+'<div class="col-lg-2 text-center text-lg-start">'
					+'<h1>Cinema</h1>'
				+'</div>'
				+'<div class="col-lg-7">'
					+'<form>'
						+'<div class="row">'
							+'<div class="col-10 pe-1">'
								+'<input type="text" class="form-control" id="recherche" placeholder="Rechercher un film">'
							+'</div>'
							+'<div class="col-2 ps-1">'
								+'<button type="button" class="btn btn-outline-secondary"><i class="fa fa-search"></i></button>'
							+'</div>'
						+'</div>'
					+'</form>'
				+'</div>'
				+'<div class="col-lg-3 text-center text-lg-start mt-2 mt-lg-0">'
					+'<button type="button" class="btn btn-success m-2" data-bs-toggle="modal" data-bs-target="#modal_connexion">Connexion</button>'
					+'<div class="modal fade" id="modal_connexion" tabindex="-1" aria-hidden="true">'
					+' <div class="modal-dialog">'
						+'<div class="modal-content">'
						+'<div class="modal-header">'
							+'<h5 class="modal-title" id="exampleModalLabel">Connectez-vous !</h5>'
							+'<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>'
						+'</div>'
						+'<div class="modal-body">'
							+'<form action="/connexion" method="POST">'
								+'<label for="labelInputPseudo" class="form-label">Pseudo</label>'
								+'<input type="text" class="form-control" id="inputPseudo" name="inputPseudo">'
								+'<label for="labelInputPwd" class="form-label">Mot de passe</label>'
								+'<input type="text" class="form-control" id="inputPseudo" name="inputPwd">'
							+'</form>'
						+'</div>'
						+'<div class="modal-footer">'
							+'<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>'
							+'<button type="button" class="btn btn-success">Connexion</button>'
						+'</div>'
						+'</div>'
					+'</div>'
					+'</div>'
					+'<button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#modal_inscription">Inscription</button>'
					+'<div class="modal fade" id="modal_inscription" tabindex="-1" aria-hidden="true">'
					+'<div class="modal-dialog">'
						+'<div class="modal-content">'
						+'<div class="modal-header">'
							+'<h5 class="modal-title" id="exampleModalLabel">Rejoignez-nous !</h5>'
							+'<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>'
						+'</div>'
						+'<div class="modal-body">'
							+'<form>'
								+'<label for="labelInputPseudo" class="form-label">Pseudo</label>'
								+'<input type="text" class="form-control" id="inputPseudo">'
								+'<label for="labelInputPwd" class="form-label">Mot de passe</label>'
								+'<input type="text" class="form-control" id="inputPwd">'
							+'</form>'
						+'</div>'
						+'<div class="modal-footer">'
							+'<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>'
							+'<button type="button" class="btn btn-success">Créer le compte</button>'
						+'</div>'
						+'</div>'
					+'</div>'
					+'</div>'
				+'</div>'
			+'</div>',
});
let app1 = new Vue({
	el: '#app',
});